name: Deploy Marp Slides to GitHub Pages

on:
  push:
    branches:
      - main # Change to 'master' if your default branch is named 'master'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # The action automatically compiles and packages everything into an upload folder
      - name: Build Marp Slides
        uses: KoharaKazuya/marp-cli-action@v4
        with:
          args: ryanhill_pinterest_presentation.md -o index.html --html --bespoke.osc=false --allow-local-files

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .marp-cli-action # This is the hidden folder the action naturally creates

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
